-- AlterTable
ALTER TABLE "session" ADD COLUMN     "COMPANY_UUID" TEXT,
ADD COLUMN     "EMPLOYEE_UUID" TEXT;

-- AddForeignKey
ALTER TABLE "session" ADD CONSTRAINT "session_COMPANY_UUID_fkey" FOREIGN KEY ("COMPANY_UUID") REFERENCES "company"("COMPANY_UUID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "session" ADD CONSTRAINT "session_EMPLOYEE_UUID_fkey" FOREIGN KEY ("EMPLOYEE_UUID") REFERENCES "employee"("EMPLOYEE_UUID") ON DELETE SET NULL ON UPDATE CASCADE;
