-- CreateTable
CREATE TABLE "orders" (
    "ORDER_UUID" TEXT NOT NULL,
    "ORDER_NAME" VARCHAR(100) NOT NULL,
    "ORDER_DESCRIPTION" VARCHAR(255) NOT NULL,
    "ORDER_AMOUNT" INTEGER NOT NULL,
    "ORDER_STATUS" VARCHAR(100) NOT NULL,
    "ORDER_CREATION_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ORDER_UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "TABLE_UUID" TEXT NOT NULL,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("ORDER_UUID")
);

-- CreateTable
CREATE TABLE "bills" (
    "BILL_UUID" TEXT NOT NULL,
    "BILL_NAME" VARCHAR(100) NOT NULL,
    "BILL_DETAILS" VARCHAR(100) NOT NULL,
    "BILL_STATUS" VARCHAR(100) NOT NULL,
    "BILL_AMOUNT" INTEGER NOT NULL,
    "BILL_CREATION_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "BILL_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "bills_pkey" PRIMARY KEY ("BILL_UUID")
);

-- CreateTable
CREATE TABLE "table_order_relation" (
    "RELATION_UUID" TEXT NOT NULL,
    "EMPLOYEE_UUID" TEXT NOT NULL,
    "CUSTOMER_UUID" TEXT,
    "TABLE_UUID" TEXT,
    "ORDER_UUID" TEXT,
    "BILL_UUID" TEXT,

    CONSTRAINT "table_order_relation_pkey" PRIMARY KEY ("RELATION_UUID")
);

-- AddForeignKey
ALTER TABLE "orders" ADD CONSTRAINT "orders_TABLE_UUID_fkey" FOREIGN KEY ("TABLE_UUID") REFERENCES "table"("TABLE_UUID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "table_order_relation" ADD CONSTRAINT "table_order_relation_EMPLOYEE_UUID_fkey" FOREIGN KEY ("EMPLOYEE_UUID") REFERENCES "employee"("EMPLOYEE_UUID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "table_order_relation" ADD CONSTRAINT "table_order_relation_CUSTOMER_UUID_fkey" FOREIGN KEY ("CUSTOMER_UUID") REFERENCES "customer"("CUSTOMER_UUID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "table_order_relation" ADD CONSTRAINT "table_order_relation_BILL_UUID_fkey" FOREIGN KEY ("BILL_UUID") REFERENCES "bills"("BILL_UUID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "table_order_relation" ADD CONSTRAINT "table_order_relation_TABLE_UUID_fkey" FOREIGN KEY ("TABLE_UUID") REFERENCES "table"("TABLE_UUID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "table_order_relation" ADD CONSTRAINT "table_order_relation_ORDER_UUID_fkey" FOREIGN KEY ("ORDER_UUID") REFERENCES "orders"("ORDER_UUID") ON DELETE SET NULL ON UPDATE CASCADE;
