-- AlterTable
ALTER TABLE "employee" ALTER COLUMN "USER_UUID" DROP NOT NULL;

-- CreateTable
CREATE TABLE "order" (
    "ORDER_UUID" TEXT NOT NULL,
    "MENU_UUID" TEXT,
    "STATUS" VARCHAR(100) NOT NULL,
    "INSTRUCTIONS" VARCHAR(255) NOT NULL,

    CONSTRAINT "order_pkey" PRIMARY KEY ("ORDER_UUID")
);

-- AddForeignKey
ALTER TABLE "order" ADD CONSTRAINT "order_MENU_UUID_fkey" FOREIGN KEY ("MENU_UUID") REFERENCES "menu"("MENU_UUID") ON DELETE SET NULL ON UPDATE CASCADE;
