-- CreateTable
CREATE TABLE "bill" (
    "BILL_UUID" TEXT NOT NULL,
    "STATUS" VARCHAR NOT NULL,
    "AMOUNT" INTEGER NOT NULL,

    CONSTRAINT "bill_pkey" PRIMARY KEY ("BILL_UUID")
);

-- CreateTable
CREATE TABLE "session" (
    "SESSION_UUID" TEXT NOT NULL,
    "TABLE_UUID" TEXT,
    "ORDER_UUID" TEXT,
    "BILL_UUID" TEXT,

    CONSTRAINT "session_pkey" PRIMARY KEY ("SESSION_UUID")
);

-- AddForeignKey
ALTER TABLE "session" ADD CONSTRAINT "session_TABLE_UUID_fkey" FOREIGN KEY ("TABLE_UUID") REFERENCES "table"("TABLE_UUID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "session" ADD CONSTRAINT "session_ORDER_UUID_fkey" FOREIGN KEY ("ORDER_UUID") REFERENCES "order"("ORDER_UUID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "session" ADD CONSTRAINT "session_BILL_UUID_fkey" FOREIGN KEY ("BILL_UUID") REFERENCES "bill"("BILL_UUID") ON DELETE SET NULL ON UPDATE CASCADE;
