-- AlterTable
ALTER TABLE "order" ADD COLUMN     "TABLE_UUID" TEXT;

-- AddForeignKey
ALTER TABLE "order" ADD CONSTRAINT "order_TABLE_UUID_fkey" FOREIGN KEY ("TABLE_UUID") REFERENCES "table"("TABLE_UUID") ON DELETE SET NULL ON UPDATE CASCADE;
