/*
  Warnings:

  - You are about to drop the column `USER_TYPE` on the `user` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "bills" ADD COLUMN     "COMPANY_UUID" TEXT;

-- AlterTable
ALTER TABLE "employee" ADD COLUMN     "COMPANY_UUID" TEXT;

-- AlterTable
ALTER TABLE "orders" ADD COLUMN     "COMPANY_UUID" TEXT;

-- AlterTable
ALTER TABLE "table" ADD COLUMN     "COMPANY_UUID" TEXT;

-- AlterTable
ALTER TABLE "table_order_relation" ADD COLUMN     "COMPANY_UUID" TEXT;

-- AlterTable
ALTER TABLE "user" DROP COLUMN "USER_TYPE";

-- CreateTable
CREATE TABLE "company" (
    "COMPANY_UUID" TEXT NOT NULL,
    "COMPANY_NAME" VARCHAR(100) NOT NULL,
    "COMPANY_ADDRESS" VARCHAR(400) NOT NULL,
    "COMPANY_ADMIN" TEXT,
    "USER_UUID" TEXT,

    CONSTRAINT "company_pkey" PRIMARY KEY ("COMPANY_UUID")
);

-- AddForeignKey
ALTER TABLE "company" ADD CONSTRAINT "company_USER_UUID_fkey" FOREIGN KEY ("USER_UUID") REFERENCES "user"("USER_UUID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "employee" ADD CONSTRAINT "employee_COMPANY_UUID_fkey" FOREIGN KEY ("COMPANY_UUID") REFERENCES "company"("COMPANY_UUID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "table" ADD CONSTRAINT "table_COMPANY_UUID_fkey" FOREIGN KEY ("COMPANY_UUID") REFERENCES "company"("COMPANY_UUID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "orders" ADD CONSTRAINT "orders_COMPANY_UUID_fkey" FOREIGN KEY ("COMPANY_UUID") REFERENCES "company"("COMPANY_UUID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bills" ADD CONSTRAINT "bills_COMPANY_UUID_fkey" FOREIGN KEY ("COMPANY_UUID") REFERENCES "company"("COMPANY_UUID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "table_order_relation" ADD CONSTRAINT "table_order_relation_COMPANY_UUID_fkey" FOREIGN KEY ("COMPANY_UUID") REFERENCES "company"("COMPANY_UUID") ON DELETE SET NULL ON UPDATE CASCADE;
