/*
  Warnings:

  - Added the required column `USER_TYPE` to the `user` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE "user" ADD COLUMN     "USER_TYPE" VARCHAR(255) NOT NULL;

-- CreateTable
CREATE TABLE "employee" (
    "EMPLOYEE_UUID" TEXT NOT NULL,
    "EMPLOYEE_NAME" VARCHAR(100) NOT NULL,
    "EMPLOYEE_TYPE" VARCHAR(100) NOT NULL,
    "EMPLOYEE_SALARY" INTEGER NOT NULL,
    "EMPLOYEE_JOINING_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "EMPLOYEE_TERMINATED_DATE" INTEGER NOT NULL,
    "USER_UUID" TEXT NOT NULL,

    CONSTRAINT "employee_pkey" PRIMARY KEY ("EMPLOYEE_UUID")
);

-- CreateTable
CREATE TABLE "customer" (
    "CUSTOMER_UUID" TEXT NOT NULL,
    "USER_UUID" TEXT NOT NULL,

    CONSTRAINT "customer_pkey" PRIMARY KEY ("CUSTOMER_UUID")
);

-- CreateTable
CREATE TABLE "table" (
    "TABLE_UUID" TEXT NOT NULL,
    "TABLE_NUMBER" TEXT NOT NULL,
    "TABEL_CHAIRS" INTEGER NOT NULL,
    "TABLE_STATUS" VARCHAR(100) NOT NULL,
    "TABLE_PRICE" INTEGER NOT NULL,
    "TABLE_CREATION_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TABLE_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "table_pkey" PRIMARY KEY ("TABLE_UUID")
);

-- CreateIndex
CREATE UNIQUE INDEX "table_TABLE_NUMBER_key" ON "table"("TABLE_NUMBER");

-- AddForeignKey
ALTER TABLE "employee" ADD CONSTRAINT "employee_USER_UUID_fkey" FOREIGN KEY ("USER_UUID") REFERENCES "user"("USER_UUID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer" ADD CONSTRAINT "customer_USER_UUID_fkey" FOREIGN KEY ("USER_UUID") REFERENCES "user"("USER_UUID") ON DELETE CASCADE ON UPDATE CASCADE;
