-- CreateTable
CREATE TABLE "user" (
    "USER_UUID" TEXT NOT NULL,
    "USER_EMAIL" TEXT NOT NULL,
    "USER_NAME" VARCHAR(255) NOT NULL,
    "USER_CREATION_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USER_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "user_pkey" PRIMARY KEY ("USER_UUID")
);

-- CreateIndex
CREATE UNIQUE INDEX "user_USER_EMAIL_key" ON "user"("USER_EMAIL");
